Deprecate EOL channels instructions
NixOS/release-wiki pull request #29
Opened 2022-02-02 23:04 UTC by jonringer

2022-02-02 23:32 UTC, cole-h requested changes

2022-02-02 23:32 UTC, cole-h commented on src/Release-Process-Walkthrough.md
> +1. [EOL Channels should be deprecated](https://github.com/NixOS/nixos-org-configurations/pull/201)
There's a difference between deprecated and unmaintained now -- 21.05 became deprecated immediately after 21.11 released, but was still technically maintained. A month after 21.11 released, 21.05 became unmaintained.

https://github.com/NixOS/nixos-org-configurations/pull/192

So basically, there should be another "post-release" step that sets the previous release as "deprecated" (but *not* "unmaintained"), in addition to this  "1 month after" section.

2022-02-02 23:36 UTC, jonringer commented on src/Release-Process-Walkthrough.md
> +1. [EOL Channels should be deprecated](https://github.com/NixOS/nixos-org-configurations/pull/201)
Yea, poor wording

2022-02-02 23:51 UTC, jonringer commented on src/Release-Process-Walkthrough.md
> +1. [EOL Channels should be deprecated](https://github.com/NixOS/nixos-org-configurations/pull/201)
added deprecation step at release time

reworded EOL step to mention it being "unmaintained" instead

2022-02-02 23:53 UTC, cole-h approved these changes
LGTM, thanks :)

2022-02-03 00:16 UTC, mweinelt approved these changes

2022-02-03 00:38 UTC, merged