Document branch-off in greater details
NixOS/release-wiki pull request #40
Opened 2022-05-21 19:49 UTC by dasJ

2022-05-21 20:19 UTC, mweinelt commented on src/Branch-Off.md
> +|`stableBranch`|Boolean|`false`|
When is `stableBranch` appropriate?

2022-05-21 20:22 UTC, dasJ commented on src/Branch-Off.md
> +|`stableBranch`|Boolean|`false`|
It's part of the next chapter. The value will be set to `true` 1-2 days before the actual release because at the time of jobset creation, the release is not official but in beta

2022-05-21 20:45 UTC, vcunat commented
21.05 has low scheduling shares now, because it's not officially supported anymore.

I wonder if it's better to describe and perform the branch creation as a clone of the corresponding jobset from the previous release, with just overwriting a few parameters (branch name, `stableBranch`).

2022-05-21 21:03 UTC, mweinelt requested changes

2022-05-21 21:03 UTC, mweinelt commented on src/Branch-Off.md
> +17. Create the `backport staging-21.05` and `backport staging-21.05` [labels](https://github.com/NixOS/nixpkgs/labels) with a description of `Backport PR automatically` and `#0fafaa` as the color
```suggestion
17. Create the backport [labels](https://github.com/NixOS/nixpkgs/labels) for all new branches:
  -  `backport release-21.05`
  -  `backport staging-21.05` 
  
  Use the description `Backport PR automatically` and  the color value `#0fafaa`.
```

2022-05-21 21:03 UTC, mweinelt commented on src/Branch-Off.md
> +18. Inform the [Marketing team](https://matrix.to/#/#marketing:nixos.org) about the upcoming release
They should be aware due to the release calendar. What is the intent here?

2022-05-21 21:03 UTC, mweinelt commented on src/Branch-Off.md
> +ago.
```suggestion
For these steps "21.05" represents the current release tag and "21.11" represents the next
(6 months in the future) release tag. "20.11" is the last release which was released 6 months
ago.
```

Create these (or similar) variables and use them in all commands below.

```
export VERYOLD=20.11
export OLD=21.05
export NEW=21.11
```

2022-05-21 21:11 UTC, dasJ commented on src/Branch-Off.md
> +13. Commit the changes
Hmm, doesn't seem like this was done in one commit previously. Will create an example commit in the next days and link it ;)

2022-05-21 21:12 UTC, dasJ commented on src/Branch-Off.md
> +14. Tag master branch so that `git describe` shows the correct metadata.
Huh? Pretty much this:
```
$ git describe master
22.05-pre-45335-g7af10ab6602
```

2022-05-21 21:14 UTC, dasJ commented on src/Branch-Off.md
> +    `nixos-org-configurations`, changing [`channels.nix`](https://github.com/NixOS/nixos-org-configurations/blob/master/channels.nix) and notify the infrastructure team
I expanded the text a bit and will add a reference PR once I created the 22.05 one

2022-05-21 21:16 UTC, dasJ commented on src/Branch-Off.md
> +18. Inform the [Marketing team](https://matrix.to/#/#marketing:nixos.org) about the upcoming release
I talked to Aaron about this and he told me to better remind them because there is no GO/NO-GO meeting anymore where they would get a reminder that the next release will be out soon.

2022-05-21 21:18 UTC, dasJ commented on src/Branch-Off.md
> +ago.
more like `PREVVER`, `CURVER`, `NEXTVER`? Because what you're referring to as `NEW` is in fact not the version that is being released but rather next one.

2022-05-21 21:28 UTC, mweinelt commented on src/Branch-Off.md
> +14. Tag master branch so that `git describe` shows the correct metadata.
Then add it as an example!

2022-05-23 13:05 UTC, vcunat commented
Nit: you [could](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lists) use `1.` in every item of the list to avoid renumbering all the time.  Pandoc supports `#.` which looks nicer but I don't expect GitHub to support it.

2022-05-23 14:13 UTC, mweinelt commented on src/Branch-Off.md
> +1. Fetch and check out the master branch
Waiting for the staging team was and is still marked step 1.

2022-05-23 14:13 UTC, mweinelt commented on src/Branch-Off.md
> +1. Fetch and check out the master branch
Oh no, you broke the numbering with some weird editor :D

2022-05-23 14:14 UTC, mweinelt commented on src/Branch-Off.md
> +1. Update the [periodic-merge workflow](https://github.com/NixOS/nixpkgs/blob/master/.github/workflows/periodic-merge-24h.yml) to include the new branch and commit + push master
```suggestion
1. Update the [periodic-merge workflow](https://github.com/NixOS/nixpkgs/blob/master/.github/workflows/periodic-merge-24h.yml) to include the new branch, then commit & push to master
```

2022-05-23 14:25 UTC, mweinelt commented on src/Branch-Off.md
> +1. Fetch and check out the master branch
Weird numbering, but looks fine when rendered.

2022-05-23 14:31 UTC, vcunat commented on src/Branch-Off.md
> +1. Fetch and check out the master branch
It's likely that even further in future there will be changes in this list, and it would be quite a bother to keep the numbers consistent in the source.

2022-05-23 18:31 UTC, merged